spring.application.name=gesture
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#logging
logging.level.chainsawman.gesture=INFO
logging.level.org.springframework.web=WARN

server.port=8082

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

spring.profiles.active=local

#baseUrl
server.servlet.context-path=/internal

# s3
aws.s3.bucket=${AWS_S3_BUCKET}
aws.region=${AWS_REGION}

# redis
spring.data.redis.port=6379