spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jwt.private-key=file:/app/keys/private_key.pem
spring.jwt.public-key=file:/app/keys/public_key.pem

server.port=8082
server.servlet.context-path=/internal

spring.jpa.show-sql=false
aws.disable-ec2-metadata=false
logging.level.chainsawman.gesture=INFO
logging.level.org.springframework.web=WARN

#swagger delete
springdoc.swagger-ui.enabled=false
