spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jwt.private-key=${JWT_PRIVATE_KEY}
spring.jwt.public-key=${JWT_PUBLIC_KEY}

server.port=8082
server.servlet.context-path=/internal

# sql log
spring.jpa.show-sql=true

#swagger delete
springdoc.swagger-ui.enabled=false
