spring.application.name=gesture
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#logging
logging.level.chainsawman.gesture=DEBUG
logging.level.org.springframework.web=DEBUG

server.port=8082

spring.profiles.active=local

#baseUrl
server.servlet.context-path=/internal
