spring.datasource.url=jdbc:mysql://3.35.173.178:3306/gesture?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=gestureuser
spring.datasource.password=Gesture1234!


server.port=8082
server.servlet.context-path=/internal

#swagger delete
springdoc.swagger-ui.enabled=false